# Basic
title: Gladiator Lee
subtitle: 李威江写字的地方
welcome_message: 今天，你写代码了吗 ^_^
description: My Little Blog on Github ！
# creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/Gladiator566'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: GladiatorLee
    github: Gladiator566
    mail: GladiatorEric666@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
